apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: webapp-image
  namespace: default
spec:
  # Enter the full patch for your container repository where you want to publish your application's image
  tag:
  serviceAccountName: kpack-service-account
  builder:
    name: builder
    kind: Builder
  source:
    git:
      # Enter the Github repo where your application source is stored
      url: https://github.com/sample-accelerators/tanzu-java-web-app
      revision: main