---
registry:
  server: https://index.docker.io/v1/
  username: 
  password: 

service_account_name: default
image_prefix: ellinj/demo-

kpack:
  # credentials for the container registry you'll be using to store images
  builder:
    # path to the container repository where kpack build artifacts are stored
    tag: ellinj/builder
  # A comma-separated list of languages e.g. [java,nodejs] that will be supported for development
  # Allowed values are:
  # - java
  # - nodejs
  # - dotnet-core
  # - go
  # - ruby
  # - php
  languages: [java]

vendir:
  # For installation of CLI binaries
  host:
    # os: darwin, linux, windows
    os: "darwin"
    # arch: amd64, arm64
    arch: "amd64"
  # getLatest overrides declared versions (disable using getLatest: "")
  getLatest: ""
  versions:
    cartographer: 0.1.0-rc.1
    cert-manager: 1.5.3
    flux2: 0.24.1
    kn: 1.1.0
    kp: 0.4.2
    kpack: 0.5.0
    kubectl: 1.23.1
    secretgen-controller: 0.6.0
    tce: 0.9.1
    yq: 4.16.1

# knative config
envoy:
  service:
    type: ClusterIP
domain:
  name: 127-0-0-1.nip.io
  type: real

cartographer:
  source_controller_version: 0.19.2
