#@ load("@ytt:data", "data")

apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: builder
  namespace: default
spec:
  serviceAccountName: kpack-service-account
  tag: #@ data.values.kpack.builder.tag
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
#@ for language in data.values.kpack.languages:
  - group:
    - id: #@ "paketo-buildpacks/{}".format(language)
#@ end
