#@ load("@ytt:data", "data")
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: tutorial-image
  namespace: default
spec:
  tag:  #@ data.values.tbs.sample.tag
  serviceAccountName: tutorial-service-account
  builder:
    name: my-builder
    kind: Builder
  source:
    git:
      url: #@ data.values.tbs.sample.url
      revision: #@ data.values.tbs.sample.revision
