#@data/values
---
kpack:
  version: 0.4.3
  # credentials for the container registry you'll be using to store images
  registry:
    username:
    password:
    url: https://index.docker.io/v1/
  builder:
    # path to the container repository where kpack build artifacts are stored
    tag:
  # A comma-separated list of languages e.g. [java,nodejs] that will be supported for development
  # Allowed values are:
  # - java
  # - nodejs
  # - dotnet-core
  # - go
  # - ruby
  # - php
  languages: [java]
