#@data/values
---
tbs:
  version: 0.4.2
  registry:
    username: 
    password: 
    url: https://index.docker.io/v1/
  builder:
   tag: 
  sample:
    tag: 
    url: https://github.com/spring-projects/spring-petclinic
    revision: 82cb521d636b282340378d80a6307a08e3d4a4c4
