#@ load("@ytt:data", "data")

#! For more info on setting semver constraints, see:
#!   https://carvel.dev/vendir/docs/latest/versions
#!   https://github.com/blang/semver#ranges
#@ def getConstraint(key):
#@   if data.values.vendir.getLatest:
#@     return ">0.0.0"
#@   else:
#@     return versions[key]
#@   end
#@ end

#@ versions = {
#@ "cert-manager": "1.5.3",
#@ "secretgen-controller": "0.6.0",
#@ "cartographer": "0.0.8-rc.7",
#@ "flux2": "0.24.1",
#@ "kpack": "0.4.3",
#@ "yq": "4.16.1",
#@ "ytt": "0.38.0",
#@ "kapp": "0.43.0",
#@ "kn": "1.1.0",
#@ "tce": "0.9.1",
#@ "kp": "0.4.2",
#@ "kubectl": "1.23.1",
#@ }

#@ os = data.values.vendir.host.os or "darwin"
#@ arch = data.values.vendir.host.arch or "amd64"
---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.8.0
directories:
  #! Product release files
  - path: vendir/cert-manager
    contents:
    - path: .
      githubRelease:
        slug: jetstack/cert-manager
        tagSelection:
          semver:
            constraints: #@ getConstraint("cert-manager")
        assetNames: [ "cert-manager.yaml" ]
        disableAutoChecksumValidation: true
  - path: vendir/secretgen-controller
    contents:
    - path: .
      githubRelease:
        slug: vmware-tanzu/carvel-secretgen-controller
        tagSelection:
          semver:
            constraints: #@ getConstraint("secretgen-controller")
        assetNames: ["release.yml"]
        disableAutoChecksumValidation: true
  - path: vendir/cartographer
    contents:
    - path: .
      githubRelease:
        slug: vmware-tanzu/cartographer
        tagSelection:
          semver:
            constraints: #@ getConstraint("cartographer")
            prereleases:
              identifiers: [ "rc" ]
        assetNames: ["cartographer.yaml"]
        disableAutoChecksumValidation: true
  - path: vendir/flux2
    contents:
    - path: .
      githubRelease:
        slug: fluxcd/flux2
        tagSelection:
          semver:
            constraints: #@ getConstraint("flux2")
        assetNames: ["install.yaml"]
        disableAutoChecksumValidation: true
  - path: vendir/kpack
    contents:
    - path: .
      githubRelease:
        slug: pivotal/kpack
        tagSelection:
          semver:
            constraints: #@ getConstraint("kpack")
        assetNames:
          - #@ "release-*.yaml"
        disableAutoChecksumValidation: true
  #! Binaries
  - path: vendir/binaries
    contents:
    - path: yq
      githubRelease:
        slug: mikefarah/yq
        tagSelection:
          semver:
            constraints: #@ getConstraint("yq")
        assetNames:
        - #@ "yq_" + os + "_" + arch
        disableAutoChecksumValidation: true
    - path: ytt
      githubRelease:
        slug: vmware-tanzu/carvel-ytt
        tagSelection:
          semver:
            constraints: #@ getConstraint("ytt")
        assetNames:
          - #@ "ytt-" + os + "-" + arch
        disableAutoChecksumValidation: true
    - path: kapp
      githubRelease:
        slug: vmware-tanzu/carvel-kapp
        tagSelection:
          semver:
            constraints: #@ getConstraint("kapp")
        assetNames:
        - #@ "kapp-" + os + "-" + arch
        disableAutoChecksumValidation: true
    - path: kn
      githubRelease:
        slug: knative/client
        #@ if data.values.vendir.getLatest:
        latest: true
        #@ else:
        tag: #@ "knative-v" + versions["kn"]
        #@ end
        assetNames:
        - #@ "kn-" + os + "-" + arch
        disableAutoChecksumValidation: true
    - path: kp
      githubRelease:
        slug: vmware-tanzu/kpack-cli
        tagSelection:
          semver:
            constraints: #@ getConstraint("kp")
        assetNames:
          - #@ "kp-" + os + "-*"
        disableAutoChecksumValidation: true
    - path: kubectl
      http:
        url: #@ "https://dl.k8s.io/release/v" + versions["kubectl"] + "/bin/" + os + "/" + arch + "/kubectl"
  #! TCE
  - path: vendir/binaries-tce
    contents:
    - path: .
      githubRelease:
        slug: vmware-tanzu/community-edition
        tagSelection:
          semver:
            constraints: #@ getConstraint("tce")
        assetNames:
          - #@ "tce-" + os + "-" + arch + "-v*.tar.gz"
        disableAutoChecksumValidation: true
#!        unpackArchive:
#!          path: #@ "tce-" + os + "-" + arch + "-v*.tar.gz"