#@ load("@ytt:data", "data")

#@ buildpack_versions = {
#@   "dotnet-core": "latest",
#@   "go": "latest",
#@   "java": "latest",
#@   "nodejs": "latest",
#@   "php": "latest",
#@   "ruby": "latest",
#@ }

apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: default
spec:
  sources:
#@ for language in data.values.kpack.languages:
  - image: #@ "gcr.io/paketo-buildpacks/{}:{}".format(language,buildpack_versions[language])
#@ end

